fix(room): #WCONF-68 create a room without name
OPEN-ENT-NG/webconference pull request #26
Opened 2023-11-20 15:13 UTC by Mattox0

## Describe your changes

An unnamed room cannot open. So now, the name is mandatory to create a room.
Then, this is not supposed to happen, but for security, in the back, if the name is empty the room has a default name

## Checklist tests

* Create a room
* Without name, we cannot create a room
* Even when we enter information for streaming, the button remains disabled until a name is entered

## Issue ticket number and link

[https://jira.support-ent.fr/browse/WCONF-60](https://jira.support-ent.fr/browse/WCONF-60)

## Checklist before requesting a review (magic string, indentation, comment/documentation...)

- [X] I have detailed the tests to do in my feature/fix in order to prevent consequences regressions (must specify in **Checklist tests**)
- [X] I have performed a self-review of my code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation (API Doc etc...) - (must specify in **Description** for target version)
- [ ] If it is a consequence feature, I have added thorough tests.
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] Any dependent changes have been added to this project (must specify in **Description**)

2023-11-20 15:30 UTC, qperie requested changes

2023-11-20 15:30 UTC, qperie commented on src/main/java/fr/openent/webConference/service/impl/DefaultRoomService.java
> +                .add(room.getString("name", "").isEmpty() ? "Salle de cours" : room.getString("name"))
Pour les constantes  comme 'name" et "Salle de cours" (et plein d'autres dans le futur) n'hésite pas à créer un fichier dédié

2023-11-20 15:30 UTC, qperie commented on src/main/resources/public/ts/controllers/main.ts
> +			if (!$scope.vm.room.name || $scope.vm.room.allow_streaming && (!$scope.vm.room.streaming_link || !$scope.vm.room.streaming_key)) {
En terme de logique booléenne là ça va pas faire la même chose :
(A || B) && (C || D) != A || B && (C || D)
Le && est prio du coup ton A || B && (C || D) c'est comme si t'avais écris A || (B && (C || D))

2023-11-20 16:11 UTC, Mattox0 commented on src/main/resources/public/ts/controllers/main.ts
> +			if (!$scope.vm.room.name || $scope.vm.room.allow_streaming && (!$scope.vm.room.streaming_link || !$scope.vm.room.streaming_key)) {
Justement, je veux que A || (B && (C || D))
Soit on a pas de nom, soit on check le streaming

2023-11-20 16:50 UTC, Mattox0 commented on src/main/java/fr/openent/webConference/service/impl/DefaultRoomService.java
> +                .add(room.getString("name", "").isEmpty() ? Config.ROOM_NAME_DEFAULT : room.getString("name"))
En effet ! je modifie ça

2023-11-21 08:42 UTC, qpic-cgi requested changes

2023-11-21 08:42 UTC, qpic-cgi commented on src/main/java/fr/openent/webConference/service/impl/DefaultRoomService.java
> +                .add(room.getString("name", Config.ROOM_NAME_DEFAULT).isEmpty() ? Config.ROOM_NAME_DEFAULT : room.getString("name"))
est-ce que ta PO a validé le fonctionnement d'une valeur par défaut ?

2023-11-21 08:50 UTC, Mattox0 commented on src/main/java/fr/openent/webConference/service/impl/DefaultRoomService.java
> +                .add(room.getString("name", "").isEmpty() ? Config.ROOM_NAME_DEFAULT : room.getString("name"))
Par contre je suis obligé de laisser la vérification, car le front envoie bien le paramètre `name` mais vide

2023-11-21 08:51 UTC, qpic-cgi commented on src/main/java/fr/openent/webConference/service/impl/DefaultRoomService.java
> +                .add(room.getString("name", "").isEmpty() ? Config.ROOM_NAME_DEFAULT : room.getString("name"))
exactement ! bonne remarque !

2023-11-27 09:40 UTC, qpic-cgi requested changes

2023-11-27 09:40 UTC, qpic-cgi commented on package-lock.json
Pourquoi tu as commit le package-lock ?
tu peux le supprimer

2023-11-27 09:40 UTC, qpic-cgi commented on src/main/java/fr/openent/webConference/service/impl/DefaultRoomService.java
> +            handler.handle(new Either.Left<>("Le nom de la salle ne peut pas être vide"));
DU FRANCAIS DANS DU JAVA ???? 😡

2023-11-27 09:40 UTC, qpic-cgi commented on src/main/java/fr/openent/webConference/service/impl/DefaultRoomService.java
> +        if (room.getString("name", "").isEmpty()) {
attention aux magic string

2023-11-27 09:40 UTC, qpic-cgi commented on src/main/java/fr/openent/webConference/service/impl/DefaultRoomService.java
> +                .add(room.getString("name"))
magique string

2023-11-27 09:40 UTC, qpic-cgi commented on src/main/resources/i18n/en.json
> +  "webconference.room.name.default": "Salle de cours",
pas nécessaire

2023-11-27 09:40 UTC, qpic-cgi commented on src/main/resources/i18n/fr.json
> +  "webconference.room.name.default": "Salle de cours",
pas nécessaire

2023-11-27 10:06 UTC, qpic-cgi requested changes

2023-11-27 10:06 UTC, qpic-cgi commented on src/main/java/fr/openent/webConference/service/impl/DefaultRoomService.java
> +            handler.handle(new Either.Left<>(i18n.translate(Config.ROOM_EMPTY_NAME, I18n.DEFAULT_DOMAIN, locale)));
Voici 2 exemples de la manière dont on traite une erreur:
https://github.com/OPEN-ENT-NG/webconference/blob/dev/src/main/java/fr/openent/webConference/service/impl/DefaultStructureService.java#L54
https://github.com/OPEN-ENT-NG/minibadge/blob/dev/src/main/java/fr/openent/minibadge/service/impl/DefaultBadgeAssignedStructureService.java#L98

2023-11-27 10:06 UTC, qpic-cgi commented on src/main/java/fr/openent/webConference/service/impl/DefaultRoomService.java
> +        String roomName = room.getString("name", "");
tu as toujours un magic string ici (je peux t'explique en live si tu veux, et si je ne suis pas là, tu peux voir ça avec n'importe quel autre dev).

2023-11-27 11:05 UTC, qpic-cgi requested changes

2023-11-27 11:05 UTC, qpic-cgi commented on src/main/java/fr/openent/webConference/controller/RoomController.java
> +                    handler.handle(new Either.Left<>(i18n.translate(Config.ROOM_EMPTY_NAME, I18n.DEFAULT_DOMAIN, locale)));
ne translate pas l'erreur. (comme dans les exemples précédents

2023-11-27 11:13 UTC, Mattox0 commented on src/main/java/fr/openent/webConference/controller/RoomController.java
> +                    handler.handle(new Either.Left<>(i18n.translate(Config.ROOM_EMPTY_NAME, I18n.DEFAULT_DOMAIN, locale)));
comme ça ? (j'ai push)

2023-11-27 11:17 UTC, qpic-cgi approved these changes

2023-11-27 13:58 UTC, qperie approved these changes

2023-11-27 14:05 UTC, merged